#ifndef BNS_C_CLIENT_EXAMPLE_CONFIG_H
#define BNS_C_CLIENT_EXAMPLE_CONFIG_H

/**
 * Please fill in the 128 bits (32 bytes) Hex encoded
 * private key which generated by VANITY-ETH
 */
#define PRIVATE_KEY \
  ""

/**
 * Please fill in the address. (e.g. 0x0000000000000000000000000000000000000000)
 */
#define ADDRESS ""

/** Please fill in the EMAIL of BNS Account */
#define EMAIL ""

/**
 * Please fill in the URL of BNS Server
 */
#define SERVER_URL ""  // TODO use prod server

/**
 * Please fill in the Node URL of Rinkey which generated by Infura
 */
#define NODE_URL ""

#endif  // BNS_C_CLIENT_EXAMPLE_CONFIG_H

/** Check the quickstarts document for more informations
 * PRIVATE_KEY : Generated by VANITY-ETH.
 * INDEX_VALUE_KEY : The index value is the index of clearance, please ensure
 * index value is unique 
 * NODE_URL : In order to get the onchain proof, we use
 * Rinkeby blockchain for our testing enviroment.
 */
