#ifndef BNS_C_CLIENT_EXAMPLE_CONFIG_H
#define BNS_C_CLIENT_EXAMPLE_CONFIG_H

/**
 * Please fill in the 128 bits (32 bytes) Hex encoded
 * private key which generated by VANITY-ETH
 */
#define PRIVATE_KEY \
  "0f139be0b965b213d777fc3998712a05fe2253c6ade9d5a3f3f07018754059c0"

/**
 * Please fill in the address. (e.g. 0x0000000000000000000000000000000000000000)
 */
#define ADDRESS "0xC739F4E7D24d675453D426492D785D23AE61AA37"

//#define INDEX_VALUE_KEY "0xF11f103CF88be3010fcEc835F5A973A0d847Fc35"
/** Please fill in the EMAIL of BNS Account */
#define EMAIL "overdiisc@gmail.com"

/**
 * Please fill in the URL of BNS Server
 */
#define SERVER_URL "https://azure-dev-membership.itm.monster/"  // TODO use prod server

/**
 * Please fill in the Node URL of Rinkey which generated by Infura
 */
#define NODE_URL "https://goerli.infura.io/v3/2cf7805f13764fe192eb0f02a194f6b1"

#endif  // BNS_C_CLIENT_EXAMPLE_CONFIG_H

/** Check the quickstarts document for more informations
 * PRIVATE_KEY : Generated by VANITY-ETH.
 * INDEX_VALUE_KEY : The index value is the index of clearance, please ensure
 * index value is unique NODE_URL : In order to get the onchain proof, we use
 * Rinkeby blockchain for our testing enviroment.
 */
