#ifndef BNS_C_CLIENT_EXAMPLE_CONFIG_H
#define BNS_C_CLIENT_EXAMPLE_CONFIG_H

/**
 * Please fill in the 128 bits (32 bytes) Hex encoded
 * private key which generated by VANITY-ETH
 */
#define PRIVATE_KEY \
  "3bd1e6f222d11dca696dff412c0742ecfdc55a754fc6d240e8d2173d64d870bc"

/**
 * Please fill in the address. (e.g. 0x0000000000000000000000000000000000000000)
 */
#define ADDRESS "0xF11f103CF88be3010fcEc835F5A973A0d847Fc35"

/** Please fill in the EMAIL of BNS Account */
#define EMAIL "aaron08820@gmail.com"

/**
 * Please fill in the URL of BNS Server
 */
#define SERVER_URL "https://bns.itrustmachines.com/"  // TODO use prod server

/**
 * Please fill in the Node URL of Rinkey which generated by Infura
 */
#define NODE_URL "https://mainnet.infura.io/v3/a7c826eac36f4eb8b672f110be9b08b0"

#endif  // BNS_C_CLIENT_EXAMPLE_CONFIG_H

/** Check the quickstarts document for more informations
 * PRIVATE_KEY : Generated by VANITY-ETH.
 * INDEX_VALUE_KEY : The index value is the index of clearance, please ensure
 * index value is unique 
 * NODE_URL : In order to get the onchain proof, we use
 * Rinkeby blockchain for our testing enviroment.
 */
